spring:
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
rest:
  ms-client:
    scheme: ${CLIENT_REST_SCHEME}
    host: ${CLIENT_REST_HOST}
    port: ${CLIENT_REST_PORT}
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans