server:
  port: ${PORT:8080}
  servlet:
    context-path: /ms-auth
spring:
  application:
    name: auth
management:
  tracing:
    sampling:
      probability: 1.0
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
security:
  tokens:
    access:
      ttl: 10
      time-unit: SECONDS
    refresh:
      ttl: 3
      time-unit: DAYS
    secret: b8663787bf74716e754970b68a3e31d6ee015e43ac7ca79242f7b2d227e18496