spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
rest:
  ms-client:
    scheme: http
    host: localhost
    port: 8081
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans